version: "3.9"

services:
   gateway:
     container_name: gateway
     command: java -jar target/demo-0.0.1-SNAPSHOT.jar
     build:
       context: .
       dockerfile: .docker/Dockerfile
     ports:
       - "56669:56669"
     environment:
       - appService.host=http://appservice
       - appService.port=56668
       - appService.productAPI=product

       - calculator.host=http://calculator
       - calculator.port=56667
       - calculator.VatAPI=vat


networks:
  default:
    external:
      name: myNetwork